/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TeaProduct, TranslationSet } from './types';

export const TEA_PRODUCTS: TeaProduct[] = [
  {
    id: 'royal-regime',
    name: 'Royal Regime Tea',
    nameAr: 'شاي ريجيم الملكي',
    tagline: 'Premium organic herbs crafted to support a balanced weight-management routine.',
    taglineAr: 'أعشاب عضوية فاخرة محضرة لدعم نظام متوازن للتحكم بالوزن.',
    description: 'A premium, naturally caffeine-free herbal infusion crafted from hand-picked wild Mediterranean botanicals. Each box contains 50 tea bags for a convenient daily wellness ritual.',
    descriptionAr: 'منقوع عشبي فاخر وخالٍ من الكافيين طبيعياً، محضر من أعشاب برية مختارة بعناية ونباتات البحر الأبيض المتوسط. تحتوي كل علبة على ٥٠ كيس شاي لروتين يومي مريح للعافية.',
    price: 24,
    category: 'Herbal',
    categoryAr: 'عشبي',
    origin: 'Mediterranean herbal blend',
    originAr: 'مزيج أعشاب البحر الأبيض المتوسط',
    temp: '200°F / 93°C',
    tempAr: '93° مئوية / 200° فهرنهايت',
    time: '5-6 mins',
    timeAr: '5-6 دقائق',
    rating: 4.9,
    reviews: 124,
    image: '/assets/images/2024__02__Regime_Royal_Tea-front.png'
  },
  {
    id: 'royal-evening',
    name: 'Royal Evening Tea – Chamomile',
    nameAr: 'شاي المساء الملكي - البابونج',
    tagline: 'A soothing chamomile infusion created for a peaceful evening ritual.',
    taglineAr: 'منقوع بابونج مهدئ صُمم لطقوس مسائية هادئة.',
    description: 'A calming chamomile herbal tea that helps you relax and unwind. Naturally caffeine-free, its gentle floral character makes it an ideal companion before bedtime. Each box contains 50 tea bags.',
    descriptionAr: 'شاي أعشاب البابونج المهدئ للمساعدة على الاسترخاء والراحة. خالٍ من الكافيين طبيعياً، وتجعله نكهته الزهرية اللطيفة رفيقاً مثالياً قبل النوم. تحتوي كل علبة على ٥٠ كيس شاي.',
    price: 26,
    category: 'Herbal',
    categoryAr: 'عشبي',
    origin: 'Premium chamomile blend',
    originAr: 'مزيج بابونج فاخر',
    temp: '205°F / 96°C',
    tempAr: '96° مئوية / 205° فهرنهايت',
    time: '5-6 mins',
    timeAr: '5-6 دقائق',
    rating: 4.8,
    reviews: 198,
    image: '/assets/images/2024__02__Royal_Evening_Tea_Chamomile.png'
  }
];

export const TRANSLATIONS: Record<'en' | 'ar', TranslationSet> = {
  en: {
    shop: 'SHOP',
    about: 'ABOUT',
    inspiration: 'INSPIRATION',
    contact: 'CONTACT',
    sustainability: 'SUSTAINABILITY',
    farms: 'OUR FARMS',
    search: 'SEARCH',
    account: 'ACCOUNT',
    cart: 'CART',
    cartEmpty: 'Your cart is empty.',
    heroTitle: 'The upgrade to your everyday cup of tea',
    heroSubtitle: 'Award-winning artisan teas. Plastic-free biodegradable tea bags and loose leaf tea made for your everyday.',
    heroButton: 'SHOP TEAS',
    origin: 'Origin',
    brewTemp: 'Brew Temp',
    brewTime: 'Brew Time',
    addToCart: 'ADD TO CART',
    added: 'ADDED ✓',
    qty: 'Quantity',
    price: 'Price',
    subtotal: 'Subtotal',
    checkout: 'CHECKOUT',
    checkoutSuccess: 'Order simulated successfully! Thank you for supporting Tea Associates.',
    searchPlaceholder: 'Search for teas (e.g. Lavender, Matcha, Egypt)...',
    noResults: 'No teas match your search.',
    contactName: 'Full Name',
    contactEmail: 'Email Address',
    contactPhone: 'Phone Number',
    contactLocation: 'Location',
    contactMessage: 'Message',
    contactSubmit: 'SEND MESSAGE',
    contactSuccess: 'Thank you! Your message has been received. We will get back to you shortly.',
    accountTitle: 'Tea Connoisseur Club',
    accountSubtitle: 'Manage your artisanal club rewards and order history.',
    accountLoyalty: 'Artisanal Loyalty Tier',
    accountPoints: 'Available Tea Points',
    accountHistory: 'Brew History',
    accountSignIn: 'Sign In / Register'
  },
  ar: {
    shop: 'تسوّق الشاي',
    about: 'قصتنا',
    inspiration: 'إلهام وطقوس',
    contact: 'اتصل بنا',
    sustainability: 'مسئوليتنا',
    farms: 'مزارعنا',
    search: 'بحث',
    account: 'حسابي',
    cart: 'السلة',
    cartEmpty: 'سلة المشتريات فارغة.',
    heroTitle: 'الترقية المثالية لكوب الشاي اليومي',
    heroSubtitle: 'شاي يدوي حرفي حائز على جوائز. أكياس شاي وأوراق شاي مناسبة للتحضير مصنوعة ليومك.',
    heroButton: 'تسوّق الشاي',
    origin: 'المنشأ',
    brewTemp: 'حرارة التحضير',
    brewTime: 'وقت التخمير',
    addToCart: 'إضافة إلى السلة',
    added: 'تمت الإضافة ✓',
    qty: 'الكمية',
    price: 'السعر',
    subtotal: 'المجموع الفرعي',
    checkout: 'إتمام الشراء',
    checkoutSuccess: 'تمت محاكاة الطلب بنجاح! شكراً لدعمكم شاي أسوشيتس.',
    searchPlaceholder: 'ابحث عن أنواع الشاي (مثل: لافندر، ماتشا، مصر)...',
    noResults: 'لم يتم العثور على شاي يطابق بحثك.',
    contactName: 'الاسم الكامل',
    contactEmail: 'البريد الإلكتروني',
    contactPhone: 'رقم الهاتف',
    contactLocation: 'الموقع',
    contactMessage: 'الرسالة',
    contactSubmit: 'إرسال الرسالة',
    contactSuccess: 'شكراً لك! تم استلام رسالتك. سنقوم بالرد عليك في أقرب وقت ممكن.',
    accountTitle: 'نادي متذوقي الشاي',
    accountSubtitle: 'إدارة مكافآت النادي الحرفية وتاريخ طلباتك.',
    accountLoyalty: 'فئة الولاء الحرفية',
    accountPoints: 'نقاط الشاي المتاحة',
    accountHistory: 'سجل التخمير والتحضير',
    accountSignIn: 'تسجيل الدخول / تسجيل جديد'
  }
};
