/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TeaProduct, TranslationSet } from './types';

export const TEA_PRODUCTS: TeaProduct[] = [
  {
    id: 'chamomile-blossom',
    name: 'Organic Chamomile Blossom',
    nameAr: 'بابونج عضوي نقي',
    tagline: 'Whole Egyptian chamomile flowers with a delicate honey sweetness.',
    taglineAr: 'أزهار البابونج المصرية الكاملة بحلاوة عسل رقيقة.',
    description: 'Sourced from the fertile banks of the Nile, our chamomile features exceptionally large blossoms that deliver a sweet, calming brew with notes of green apple and wildflower honey. Naturally caffeine-free, it is the perfect evening ritual.',
    descriptionAr: 'مستزرع من ضفاف النيل الخصبة، يتميز البابونج لدينا بأزهار كبيرة استثنائية تقدم كوباً مهدئاً حلواً مع نفحات من التفاح الأخضر وعسل الزهور البرية. خالٍ من الكافيين طبيعياً، وهو الطقس المثالي للمساء.',
    price: 24,
    category: 'Herbal',
    categoryAr: 'عشبي',
    origin: 'Fayoum, Egypt',
    originAr: 'الفيوم، مصر',
    temp: '205°F / 96°C',
    tempAr: '96° مئوية / 205° فهرنهايت',
    time: '5-6 mins',
    timeAr: '5-6 دقائق',
    rating: 4.9,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'lavender-earl-grey',
    name: 'French Lavender Earl Grey',
    nameAr: 'إيرل غري بالخزامى الفرنسية',
    tagline: 'Bold Yunnan black tea infused with cold-pressed bergamot and lavender.',
    taglineAr: 'شاي يونان الأسود الفاخر منقوع بزيت البرغموت واللافندر المعصور على البارد.',
    description: 'An elegant upgrade to a classic. We blend bold, organic Yunnan black tea with direct-import French blue lavender and cold-pressed oil of Italian bergamot. Rich, citrusy, and deeply aromatic with a soothing floral finish.',
    descriptionAr: 'ترقية أنيقة للشاي الكلاسيكي. نمزج شاي يونان الأسود العضوي القوي مع الخزامى الفرنسية الزرقاء المستوردة مباشرة وزيت البرغموت الإيطالي المعصور على البارد. غني، حمضي، وعطري للغاية مع لمسة زهور مهدئة.',
    price: 26,
    category: 'Black',
    categoryAr: 'أسود',
    origin: 'Yunnan, China & Provence, France',
    originAr: 'يونان، الصين وبروفانس، فرنسا',
    temp: '195°F / 90°C',
    tempAr: '90° مئوية / 195° فهرنهايت',
    time: '3-4 mins',
    timeAr: '3-4 دقائق',
    rating: 4.8,
    reviews: 198,
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600'
  }
];

export const TRANSLATIONS: Record<'en' | 'ar', TranslationSet> = {
  en: {
    shop: 'SHOP',
    subscription: 'SUBSCRIPTION',
    about: 'ABOUT',
    inspiration: 'INSPIRATION',
    contact: 'CONTACT',
    sustainability: 'SUSTAINABILITY',
    farms: 'OUR FARMS',
    search: 'SEARCH',
    account: 'ACCOUNT',
    cart: 'CART',
    cartEmpty: 'Your cart is empty.',
    heroTitle: 'The upgrade to your everyday cup of tea',
    heroSubtitle: 'Award-winning artisan teas. Plastic-free biodegradable tea bags and loose leaf tea made for your everyday.',
    heroButton: 'SHOP TEAS',
    awardGold: 'GOLD LEAF AWARD',
    awardBronze: 'BRONZE LEAF AWARD',
    awardYear: 'WINNER 2025',
    origin: 'Origin',
    brewTemp: 'Brew Temp',
    brewTime: 'Brew Time',
    addToCart: 'ADD TO CART',
    added: 'ADDED ✓',
    qty: 'Quantity',
    price: 'Price',
    subtotal: 'Subtotal',
    checkout: 'CHECKOUT',
    checkoutSuccess: 'Order simulated successfully! Thank you for supporting Tea Associates.',
    searchPlaceholder: 'Search for teas (e.g. Lavender, Matcha, Egypt)...',
    noResults: 'No teas match your search.',
    contactName: 'Full Name',
    contactEmail: 'Email Address',
    contactMessage: 'Message',
    contactSubmit: 'SEND MESSAGE',
    contactSuccess: 'Thank you! Your message has been received. We will get back to you shortly.',
    subscribeTitle: 'Artisanal Monthly Subscriptions',
    subscribeSubtitle: 'Get seasonal, hand-picked rare tea boxes delivered to your doorstep every month.',
    subscribePlanMonthly: 'The Connoisseur Box',
    subscribePlanPremium: 'The Master Curator Box',
    subscribeButton: 'SUBSCRIBE NOW',
    accountTitle: 'Tea Connoisseur Club',
    accountSubtitle: 'Manage your artisanal club rewards and order history.',
    accountLoyalty: 'Artisanal Loyalty Tier',
    accountPoints: 'Available Tea Points',
    accountHistory: 'Brew History',
    accountSignIn: 'Sign In / Register'
  },
  ar: {
    shop: 'تسوّق الشاي',
    subscription: 'الاشتراك الشهري',
    about: 'قصتنا',
    inspiration: 'إلهام وطقوس',
    contact: 'اتصل بنا',
    sustainability: 'مسئوليتنا',
    farms: 'مزارعنا',
    search: 'بحث',
    account: 'حسابي',
    cart: 'السلة',
    cartEmpty: 'سلة المشتريات فارغة.',
    heroTitle: 'الترقية المثالية لكوب الشاي اليومي',
    heroSubtitle: 'شاي يدوي حرفي حائز على جوائز. أكياس شاي قابلة للتحلل وخالية من البلاستيك وأوراق شاي سائبة مصنوعة ليومك.',
    heroButton: 'تسوّق الشاي',
    awardGold: 'جائزة الورقة الذهبية',
    awardBronze: 'جائزة الورقة البرونزية',
    awardYear: 'الفائز ٢٠٢٥',
    origin: 'المنشأ',
    brewTemp: 'حرارة التحضير',
    brewTime: 'وقت التخمير',
    addToCart: 'إضافة إلى السلة',
    added: 'تمت الإضافة ✓',
    qty: 'الكمية',
    price: 'السعر',
    subtotal: 'المجموع الفرعي',
    checkout: 'إتمام الشراء',
    checkoutSuccess: 'تمت محاكاة الطلب بنجاح! شكراً لدعمكم شاي أسوشيتس.',
    searchPlaceholder: 'ابحث عن أنواع الشاي (مثل: لافندر، ماتشا، مصر)...',
    noResults: 'لم يتم العثور على شاي يطابق بحثك.',
    contactName: 'الاسم الكامل',
    contactEmail: 'البريد الإلكتروني',
    contactMessage: 'الرسالة',
    contactSubmit: 'إرسال الرسالة',
    contactSuccess: 'شكراً لك! تم استلام رسالتك. سنقوم بالرد عليك في أقرب وقت ممكن.',
    subscribeTitle: 'الاشتراكات الشهرية الفاخرة',
    subscribeSubtitle: 'احصل على صناديق شاي نادرة ومختارة يدوياً وموسمياً يتم توصيلها إلى عتبة دارك كل شهر.',
    subscribePlanMonthly: 'صندوق المتذوقين',
    subscribePlanPremium: 'صندوق كبار المنسقين',
    subscribeButton: 'اشترك الآن',
    accountTitle: 'نادي متذوقي الشاي',
    accountSubtitle: 'إدارة مكافآت النادي الحرفية وتاريخ طلباتك.',
    accountLoyalty: 'فئة الولاء الحرفية',
    accountPoints: 'نقاط الشاي المتاحة',
    accountHistory: 'سجل التخمير والتحضير',
    accountSignIn: 'تسجيل الدخول / تسجيل جديد'
  }
};
